spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 5640000010
  secret: MY_SECRET_20230710_#2
gateway:
  ip: 127.0.0.1
